TFDIR=/storage/mgymrek/gtex/tfbs/encodedata/
TFDIRSORT=/storage/mgymrek/gtex/tfbs/encodedata/sorted
TFINDEX=/storage/mgymrek/gtex/tfbs/giggle
RNABPDIR=/storage/mgymrek/gtex/rnabps/encodedata/
RNABPSORT=/storage/mgymrek/gtex/rnabps/encodedata/sorted
RNABPINDEX=/storage/mgymrek/gtex/rnabps/giggle
ROADMAPINDEX=/storage/resources/dbase/human/hg19/GIGGLE/roadmap_sort_b # TODO also do with epigenome roadmap
TMPDIR=/storage/mgymrek/gtex/tfbs/tmp
OUTDIR=/storage/mgymrek/gtex/tfbs/enrichment
TISSUES="Cells-Transformedfibroblasts Artery-Aorta Artery-Tibial Muscle-Skeletal Nerve-Tibial Lung Brain-Cerebellum Skin-SunExposed(Lowerleg) Thyroid Heart-LeftVentricle WholeBlood Adipose-Visceral(Omentum) Esophagus-Mucosa Brain-Caudate(basalganglia) Skin-NotSunExposed(Suprapubic) Esophagus-Muscularis Adipose-Subcutaneous"
